HM-523:Resolving pipeline issue

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -108,6 +108,45 @@ k8s-low-test:
     - exists:
         - tests/**/*
 
+k8s-test:
+  # allow_failure: true
+  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
+  stage: test
+  tags:
+    - k8srunner-large
+  variables:
+    CONFIG: 'mid'
+    KUBE_NAMESPACE: 'ci-$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CONFIG'
+  before_script:
+    - '[ -f .make/k8s.mk ] || (echo "File k8s.mk not included in Makefile; exit 1")'
+    - 'make help | grep k8s-test'
+    - make k8s-install-chart
+    - make k8s-wait
+  script:
+    - make k8s-test || true
+    - |
+      if [[ "$CI_KEEP_NAMESPACE" != "true" ]]; then
+        make k8s-uninstall-chart || true
+        make k8s-delete-namespace || true
+      fi;
+    # ST-1258: Cleanup and exit if the test return code is present
+    - '[ -f build/status ] || (echo "Something went wrong with the test (no build/status file); exit 1")'
+    - exit $(cat build/status)
+  artifacts:
+    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
+    paths:
+      - "build/"
+    reports:
+      junit: build/report.xml
+    when: always
+  environment:
+    name: test/$CI_COMMIT_REF_SLUG
+    on_stop: stop-k8s-test
+    auto_stop_in: 1 minute
+  rules:
+    - exists:
+        - tests/**/*
+
 stop-k8s-test-low:
   image: $SKA_K8S_TOOLS_BUILD_DEPLOY
   stage: test
